### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by sparkjames** [joeydsmith/magento18#2]
My neck and lower jaw were removed, now my eyes are at shoulder level.

**Comment by joeydsmith** [comment]
Shit, ill get a doctor to fix that.

**Comment by joeydsmith** [comment]
![10919067_875963602445491_1642164521_n](https://cloud.githubusercontent.com/assets/4332989/6529221/291c7492-c3f5-11e4-8399-deb0ef74f844.jpg)

Completed.
